In [38]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier



In [19]:
import netCDF4
import os
import numpy as np
import matlab
import matlab.engine
eng = matlab.engine.start_matlab()
Lx = 59.39
L2x = 59.39/2
Ly = 60.018 
L2y = 60.018/2
Lz = 74.345
L2z = 74.345/2
#periodic boundary condition
def pbcx(a):
    while((a > L2x) | (a <= -L2x)):
        if(a > L2x):
            a -= Lx
        if(a <= -L2x):
            a += Lx
    return(a)
def pbcy(a):
    while((a > L2y) | (a <= -L2y)):
        if(a > L2y):
            a -= Ly
        if(a <= -L2y):
            a += Ly
    return(a)
def pbcz(a):
    while((a > L2z) | (a <= -L2z)):
        if(a > L2z):
            a -= Lz
        if(a <= -L2z):
            a += Lz
    return(a)
# build function of polar
def tensor(x1,y1,z1,x2,y2,z2):
    x = pbcx(x1 - x2)
    y = pbcy(y1 - y2)
    z = pbcz(z1 - z2)
    r = np.sqrt(x*x + y*y + z*z)
    a = np.eye(3) /(r * r * r) - np.array([[x*x,x*y,x*z],[y*x,y*y,y*z],[z*x,z*y,z*z]]) * 3 /(r * r * r * r * r)
    return a
# get coordinates of B and Cl atoms    
nc = netCDF4.Dataset('prd_hollow_1.nc')
c=nc.variables['coordinates']
d=np.zeros([72,3])
e=np.zeros([72,3])
j=0
for i in range(1501,2557,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(4101,5157,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(6701,7757,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
Xd = np.zeros(72)
Yd = np.zeros(72)
Zd = np.zeros(72)
for i in range(72):
    Xd[i] = d[i][0]
    Yd[i] = d[i][1]
    Zd[i] = d[i][2]
#calculate all Tij tensor
#calculate the A matrix, b means polarizability for a single B atom
b = np.eye(3) * 20.47
#bf = b^(-1) matrix
bf = np.linalg.inv(b)      
f = eng.cell(72)
for i in range(72):
    for j in range(72):
        if(i == j):
            f[i,j] = bf
        else:
            f[i,j] = tensor(Xd[i],Yd[i],Zd[i],Xd[j],Yd[j],Zd[j])
g = eng.cell2mat(f)
print(g)

ValueError: MATLAB 只能返回 1xN 和 Nx1 元胞数组

In [34]:
import netCDF4
nc = netCDF4.Dataset('prd_hollow_1.nc')
nc.variables.keys()

print(nc)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_64BIT_OFFSET data model, file format NETCDF3):
    title: default_name
    application: AMBER
    program: sander
    programVersion: 17.0
    Conventions: AMBER
    ConventionVersion: 1.0
    dimensions(sizes): frame(40000), spatial(3), atom(7800), cell_spatial(3), label(5), cell_angular(3)
    variables(dimensions): float32 time(frame), |S1 spatial(spatial), float32 coordinates(frame,atom,spatial), |S1 cell_spatial(cell_spatial), |S1 cell_angular(cell_angular,label), float64 cell_lengths(frame,cell_spatial), float64 cell_angles(frame,cell_angular)
    groups: 


In [ ]:
import netCDF4
import os
import numpy as np
nc = netCDF4.Dataset('prd_hollow_1.nc')
c=nc.variables['coordinates']
d=np.zeros([72,3])
e=np.zeros([72,3])
j=0
for i in range(1501,2557,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(4101,5157,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(6701,7757,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
xd = np.zeros(72)
for i in range(72):
    xd[i] = d[i][0]
print(xd)


In [23]:
# calculation of B atom's polarizability
import netCDF4
import os
import numpy as np
Lx = 59.39
L2x = 59.39/2
Ly = 60.018 
L2y = 60.018/2
Lz = 74.345
L2z = 74.345/2
#periodic boundary condition
def pbcx(a):
    while((a > L2x) | (a <= -L2x)):
        if(a > L2x):
            a -= Lx
        if(a <= -L2x):
            a += Lx
    return(a)
def pbcy(a):
    while((a > L2y) | (a <= -L2y)):
        if(a > L2y):
            a -= Ly
        if(a <= -L2y):
            a += Ly
    return(a)
def pbcz(a):
    while((a > L2z) | (a <= -L2z)):
        if(a > L2z):
            a -= Lz
        if(a <= -L2z):
            a += Lz
    return(a)
# build function of polar
def tensor(x1,y1,z1,x2,y2,z2):
    x = pbcx(x1 - x2)
    y = pbcy(y1 - y2)
    z = pbcz(z1 - z2)
    r = np.sqrt(x*x + y*y + z*z)
    a = np.eye(3) /(r * r * r) - np.array([[x*x,x*y,x*z],[y*x,y*y,y*z],[z*x,z*y,z*z]]) * 3 /(r * r * r * r * r)
    return a
# get coordinates of B and Cl atoms    
nc = netCDF4.Dataset('prd_hollow_1.nc')
c=nc.variables['coordinates']
d=np.zeros([72,3])
e=np.zeros([72,3])
j=0
for i in range(1501,2557,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(4101,5157,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(6701,7757,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
Xd = np.zeros(72)
Yd = np.zeros(72)
Zd = np.zeros(72)
for i in range(72):
    Xd[i] = d[i][0]
    Yd[i] = d[i][1]
    Zd[i] = d[i][2]
#calculate all Tij tensor
#calculate the A matrix, b means polarizability for a single B atom
b = np.eye(3) * 20.47
#bf = b^(-1) matrix
bf = np.linalg.inv(b)      
f = np.empty((72,72),dtype=object)
for i in range(72):
    for j in range(72):
        if(i == j):
            f[i][j] = bf
        else:
            f[i][j] = tensor(Xd[i],Yd[i],Zd[i],Xd[j],Yd[j],Zd[j])
#calculate the B matrix
g = np.empty((1,72),dtype=object)
for i in range(72):
    g[0][i] = f[0][i]
for i in range(72):
    for j in range(1,72):
        g[0][i] = np.vstack((g[0][i],f[j][i]))
for i in range(1,72):
    g[0][0] = np.hstack((g[0][0],g[0][i]))
B = np.linalg.inv(g[0][0])
# Partition B matrix
row = np.hsplit(B,72)
C = np.empty(72,dtype=object)
for i in range(72):
        C[i] = np.vsplit(row[i],72)
# calculate the sum of the B_ij matrix
sum = np.zeros([3,3])
for i in range(72):
    for j in range(72):
        sum += C[i][j]
print(sum)

[[1500.23283522   27.11912087   16.52234303]
 [  27.11912087 1517.77050796  -34.03919936]
 [  16.52234303  -34.03919936 1467.4373123 ]]


In [22]:
# calculation of Cl atom's polarizability
import netCDF4
import os
import numpy as np
Lx = 59.39
L2x = 59.39/2
Ly = 60.018 
L2y = 60.018/2
Lz = 74.345
L2z = 74.345/2
#periodic boundary condition
def pbcx(a):
    while((a > L2x) | (a <= -L2x)):
        if(a > L2x):
            a -= Lx
        if(a <= -L2x):
            a += Lx
    return(a)
def pbcy(a):
    while((a > L2y) | (a <= -L2y)):
        if(a > L2y):
            a -= Ly
        if(a <= -L2y):
            a += Ly
    return(a)
def pbcz(a):
    while((a > L2z) | (a <= -L2z)):
        if(a > L2z):
            a -= Lz
        if(a <= -L2z):
            a += Lz
    return(a)
# build function of polar
def tensor(x1,y1,z1,x2,y2,z2):
    x = pbcx(x1 - x2)
    y = pbcy(y1 - y2)
    z = pbcz(z1 - z2)
    r = np.sqrt(x*x + y*y + z*z)
    a = np.eye(3) /(r * r * r) - np.array([[x*x,x*y,x*z],[y*x,y*y,y*z],[z*x,z*y,z*z]]) * 3 /(r * r * r * r * r)
    return a
# get coordinates of B and Cl atoms    
nc = netCDF4.Dataset('prd_hollow_1.nc')
c=nc.variables['coordinates']
d=np.zeros([72,3])
e=np.zeros([72,3])
j=0
for i in range(1501,2557,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(4101,5157,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(6701,7757,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
Xe = np.zeros(72)
Ye = np.zeros(72)
Ze = np.zeros(72)
for i in range(72):
    Xe[i] = e[i][0]
    Ye[i] = e[i][1]
    Ze[i] = e[i][2]
#calculate all Tij tensor
#calculate the A matrix, b means polarizability for a single Cl atom
c = np.eye(3) * 14.71
#cf = c^(-1) matrix
cf = np.linalg.inv(c)      
f = np.empty((72,72),dtype=object)
for i in range(72):
    for j in range(72):
        if(i == j):
            f[i][j] = cf
        else:
            f[i][j] = tensor(Xe[i],Ye[i],Ze[i],Xe[j],Ye[j],Ze[j])
#calculate the B matrix
g = np.empty((1,72),dtype=object)
for i in range(72):
    g[0][i] = f[0][i]
for i in range(72):
    for j in range(1,72):
        g[0][i] = np.vstack((g[0][i],f[j][i]))
for i in range(1,72):
    g[0][0] = np.hstack((g[0][0],g[0][i]))
B = np.linalg.inv(g[0][0])
# Partition B matrix
row = np.hsplit(B,72)
C = np.empty(72,dtype=object)
for i in range(72):
        C[i] = np.vsplit(row[i],72)
# calculate the sum of the B_ij matrix
sum = np.zeros([3,3])
for i in range(72):
    for j in range(72):
        sum += C[i][j]
print(sum)

[[1095.74573732   13.78156785   15.25757202]
 [  13.78156785 1092.50057807  -13.6358816 ]
 [  15.25757202  -13.6358816  1044.92939055]]


In [29]:
# calculation of Cl,B atom's polarizability
import netCDF4
import os
import numpy as np
Lx = 59.39
L2x = 59.39/2
Ly = 60.018 
L2y = 60.018/2
Lz = 74.345
L2z = 74.345/2
#periodic boundary condition
def pbcx(a):
    while((a > L2x) | (a <= -L2x)):
        if(a > L2x):
            a -= Lx
        if(a <= -L2x):
            a += Lx
    return(a)
def pbcy(a):
    while((a > L2y) | (a <= -L2y)):
        if(a > L2y):
            a -= Ly
        if(a <= -L2y):
            a += Ly
    return(a)
def pbcz(a):
    while((a > L2z) | (a <= -L2z)):
        if(a > L2z):
            a -= Lz
        if(a <= -L2z):
            a += Lz
    return(a)
# build function of polar
def tensor(x1,y1,z1,x2,y2,z2):
    x = pbcx(x1 - x2)
    y = pbcy(y1 - y2)
    z = pbcz(z1 - z2)
    r = np.sqrt(x*x + y*y + z*z)
    a = np.eye(3) /(r * r * r) - np.array([[x*x,x*y,x*z],[y*x,y*y,y*z],[z*x,z*y,z*z]]) * 3 /(r * r * r * r * r)
    return a
# get coordinates of B and Cl atoms    
nc = netCDF4.Dataset('prd_hollow_1.nc')
c=nc.variables['coordinates']
d=np.zeros([72,3])
e=np.zeros([72,3])
j=0
for i in range(1501,2557,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(4101,5157,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
for i in range(6701,7757,44):
    d[j]=c[0,i]
    e[j]=c[0,i-1]
    j+=1
Xe = np.zeros(144)
Ye = np.zeros(144)
Ze = np.zeros(144)
for i in range(72):
    Xe[i] = e[i][0]
    Ye[i] = e[i][1]
    Ze[i] = e[i][2]
for i in range(72,144):
    Xe[i] = d[i-72][0]
    Ye[i] = d[i-72][1]
    Ze[i] = d[i-72][2]
#b is the polarizability of single Cl atom, c is the polariability f single B atom
b = np.eye(3) * 20.47
#bf = b^(-1) matrix
bf = np.linalg.inv(b)
c = np.eye(3) * 14.71
#cf = c^(-1) matrix
cf = np.linalg.inv(c)
f = np.empty((144,144),dtype=object)
for i in range(72):
    for j in range(72):
        if(i == j):
            f[i][j] = cf
for i in range(72,144):
    for j in range(72,144):
        if(i == j):
            f[i][j] = bf
for i in range(144):
    for j in range(144):
        if(i != j):
            f[i][j] = tensor(Xe[i],Ye[i],Ze[i],Xe[j],Ye[j],Ze[j])
#calculate the B matrix
g = np.empty((1,144),dtype=object)
for i in range(144):
    g[0][i] = f[0][i]
for i in range(144):
    for j in range(1,144):
        g[0][i] = np.vstack((g[0][i],f[j][i]))
for i in range(1,144):
    g[0][0] = np.hstack((g[0][0],g[0][i]))
B = np.linalg.inv(g[0][0])
# Partition B matrix
row = np.hsplit(B,144)
C = np.empty(144,dtype=object)
for i in range(144):
        C[i] = np.vsplit(row[i],144)
# calculate the sum of the B_ij matrix
sum = np.zeros([3,3])
for i in range(144):
    for j in range(144):
        sum += C[i][j]
print(sum)            

[[301.53713264  17.44200036  -3.51555012]
 [ 17.44200036 228.67983148 -24.05604332]
 [ -3.51555012 -24.05604332 250.14844221]]


In [16]:
#benchmark flu check
import numpy as np
#function of tensor
def tensor(x1,y1,z1,x2,y2,z2):
    x = abs(x1 - x2)
    y = abs(y1 - y2)
    z = abs(z1 - z2)
    r = np.sqrt(x*x + y*y + z*z)
    a = np.eye(3) /(r * r * r) - np.array([[x*x,x*y,x*z],[y*x,y*y,y*z],[z*x,z*y,z*z]]) * 3 /(r * r * r * r * r)
    return a
# calculate the H and C atom alpha
h = np.eye(3) * 4.5
hf = np.linalg.inv(h)
c = np.eye(3) * 11.39
cf = np.linalg.inv(c)
a = np.loadtxt('bench.txt')
# calculate the A matrix
f = np.empty((21,21),dtype=object)
for i in range(11):
    for j in range(11):
        if(i == j):
            f[i][j] = cf
for i in range(11,21):
    for j in range(11,21):
        if(i == j):
            f[i][j] = hf
for i in range(21):
    for j in range(21):
        if(i != j):
            f[i][j] = tensor(a[i][0],a[i][1],a[i][2],a[j][0],a[j][1],a[j][2])
#calculate the B matrix
g = np.empty((1,21),dtype=object)
for i in range(21):
    g[0][i] = f[0][i]
for i in range(21):
    for j in range(1,21):
        g[0][i] = np.vstack((g[0][i],f[j][i]))
for i in range(1,21):
    g[0][0] = np.hstack((g[0][0],g[0][i]))
B = np.linalg.inv(g[0][0])
# Partition B matrix
row = np.hsplit(B,21)
C = np.empty(21,dtype=object)
for i in range(21):
        C[i] = np.vsplit(row[i],21)
# calculate the sum of the B_ij matrix
sum = np.zeros([3,3])
for i in range(21):
    for j in range(21):
        sum += C[i][j]
print(sum)                        

[[ 2.47907630e+00 -1.18200628e+01 -3.63876917e-03]
 [-1.18200628e+01  2.67640615e+00 -4.98120261e-03]
 [-3.63876917e-03 -4.98120261e-03  1.13139520e+01]]


In [1]:
#32 Xe
import numpy as np
L = pow(32/0.8,1/3) * 4.19
L2 = L/2
def pbc(a):
    while((a > L2) | (a <= -L2)):
        if(a > L2):
            a -= L
        if(a <= -L2):
            a += L
    return(a)
def tensor(x1,y1,z1,x2,y2,z2):
    x = pbc(x1 - x2)
    y = pbc(y1 - y2)
    z = pbc(z1 - z2)
    r = np.sqrt(x*x + y*y + z*z)
    a = np.eye(3) /(r * r * r) - np.array([[x*x,x*y,x*z],[y*x,y*y,y*z],[z*x,z*y,z*z]]) * 3 /(r * r * r * r * r)
    return a
x = np.loadtxt('Xe.txt')
xe = np.eye(3) * 4.11
xef = np.linalg.inv(xe)
f = np.empty((32,32),dtype=object)
for i in range(32):
    for j in range(32):
        if(i ==j):
            f[i][j] = xef
        else:
            f[i][j] = tensor(x[i][0],x[i][1],x[i][2],x[j][0],x[j][1],x[j][2])
g = np.empty((1,32),dtype=object)
for i in range(32):
    g[0][i] = f[0][i]
for i in range(32):
    for j in range(1,32):
        g[0][i] = np.vstack((g[0][i],f[j][i]))
for i in range(1,32):
    g[0][0] = np.hstack((g[0][0],g[0][i]))
B = np.linalg.inv(g[0][0])
# Partition B matrix
row = np.hsplit(B,32)
C = np.empty(32,dtype=object)
for i in range(32):
        C[i] = np.vsplit(row[i],32)
# calculate the sum of the B_ij matrix
sum = np.zeros([3,3])     
for i in range(32):
    for j in range(32):
        sum += C[i][j]
print(sum)    

[[ 20.74945478   5.60627418 -10.58030692]
 [  5.60627418 -35.57372411 -34.49717269]
 [-10.58030692 -34.49717269  57.59971664]]
